addressing review comments
paromita-d/project-library pull request #5
Opened 2020-09-29 03:09 UTC by paromita-d

addressing review comments from https://github.com/paromita-d/project-library/issues/4

2020-09-29 20:24 UTC, NateHand93 requested changes
Everything that's been changed so far looks good.

However, one thing is still pending: cleaning up those `catch (Exception e)` blocks that you are re-throwing as `LibraryException`s. Any runtime exceptions thrown from your service classes will be handled by the `handleRunTimeException()` method in your `LibraryErrorAdvice` class anyway, and in those cases, they probably _are_ server-side exceptions

2020-10-10 13:07 UTC, paromita-d commented
> Everything that's been changed so far looks good.
> 
> However, one thing is still pending: cleaning up those `catch (Exception e)` blocks that you are re-throwing as `LibraryException`s. Any runtime exceptions thrown from your service classes will be handled by the `handleRunTimeException()` method in your `LibraryErrorAdvice` class anyway, and in those cases, they probably _are_ server-side exceptions

@NateHand93 fixed as per comments. Please review

2020-10-16 14:32 UTC, NateHand93 commented on library-be/src/main/java/org/library/service/MetaDataService.java
> +        if(optional.isPresent())
This would have been a perfect opportunity to use the `orElseThrow()` method. Lines 29 through 33 could be replaced with `return repository.findById(CHECKOUT_DURATION).orElseThrow(() -> new LibraryException(CHECKOUT_DURATION + " not found in DB");`

This looks good though. No need to change it. Just letting you know for future reference

2020-10-16 14:32 UTC, NateHand93 approved these changes
LGTM

2020-10-18 02:17 UTC, merged